2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Configure stats pid to 40347
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/.config/wandb/settings
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/settings
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-26 23:46:17,662 INFO    MainThread:40347 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_log_setup():478] Logging user logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234617-1lf98bal/logs/debug.log
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_log_setup():479] Logging internal logs to /Users/rishubtamirisa/UIUC/NNProjects/transformer/language-model-impl/wandb/offline-run-20230126_234617-1lf98bal/logs/debug-internal.log
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:_jupyter_setup():428] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x2b5b88880>
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():518] calling init triggers
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {'learning_rate': 5e-05, 'architecture': 'Transformer', 'dataset': 'wikitext-2', 'epochs': 4}
2023-01-26 23:46:17,663 INFO    MainThread:40347 [wandb_init.py:init():537] re-initializing run, found existing run on stack: dzeu2tsp
2023-01-26 23:46:17,664 INFO    MainThread:40347 [wandb_run.py:_finish():1844] finishing run encoder-mlm/dzeu2tsp
2023-01-26 23:46:17,664 ERROR   MainThread:40347 [jupyter.py:save_history():441] Run pip install nbformat to save notebook history
2023-01-26 23:46:17,664 INFO    MainThread:40347 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2023-01-26 23:46:17,664 INFO    MainThread:40347 [wandb_init.py:_jupyter_teardown():410] cleaning up jupyter logic
2023-01-26 23:46:17,672 ERROR   MainThread:40347 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 550, in init
    self._wl._global_run_stack[-1].finish()
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 370, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 333, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1835, in finish
    return self._finish(exit_code, quiet)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1863, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 187, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 54, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/rishubtamirisa/miniforge3/envs/LM-impl/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
